name: Test

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release tag
        required: true
      debug:
        description: Enable debug mode when set to 'true'
        required: false
        default: "false"

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Set debug mode
        if: ${{ github.event.inputs.debug == 'true' }}
        run: |
          set -x
      - name: Set up environment
        env:
          TAG: "${{ github.event.inputs.tag }}"
        run: |
          echo "branch=$( echo "${TAG}" | cut -d '.' -f '-2' )" >> "${GITHUB_ENV}"
          echo "date=$(date +%F)" >> "${GITHUB_ENV}"
      - name: Check out docs
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: "./lorawan-stack-docs"
          repository: happyRip/lorawan-stack-docs
      - name: Check out lorawan stack
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: "./lorawan-stack"
          # ref: "${{ github.event.inputs.tag }}"
          ref: "${{ env.branch }}"
          repository: happyRip/lorawan-stack
          ssh-key: "${{ secrets.LORAWAN_STACK_SSH_KEY }}"
      - name: Check out lorawan stack aws
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: "./lorawan-stack-aws"
          # ref: "${{ github.event.inputs.tag }}"
          ref: "${{ env.branch }}"
          repository: happyRip/lorawan-stack-aws
          ssh-key: "${{ secrets.LORAWAN_STACK_AWS_SSH_KEY }}"
      - name: Update changelog
        working-directory: "./lorawan-stack-docs"
        env:
          BRANCH: "${{ env.branch }}"
          DATE: "${{ env.date }}"
          TAG: "${{ github.event.inputs.tag }}"
        run: |
          cp ../lorawan-stack/CHANGELOG.md .

          # Get changes
          TMP_FILE=$(mktemp)
          sed -n '/## \[Unreleased\]/,/## \[/p' 'CHANGELOG.md' \
            | tail -n +3 \
            | head -n -1 \
            > "${TMP_FILE}"

          # Remove empty sections
          remove_empty_sections() {
            local BUFFER INPUT_FILE="$1"
            local P=true # to-print flag

            while read -r l; do
              if [[ ${l} =~ ^###[^#] ]]; then              # if new section
                [ ${P} = true ] && printf "%s" "${BUFFER}" # if to-print, print buffer
                BUFFER="${l}"$'\n'                         # reset buffer
                P=false                                    # reset to-print flag
              else
                BUFFER="${BUFFER}${l}"$'\n' # update buffer
                [[ -n ${l} ]] && P=true     # if non-empty line, set to-print flag
              fi
            done <"${INPUT_FILE}"
            [ ${P} = true ] && printf "%s" "${BUFFER}" # if to-print, print buffer
          }

          CHANGES_FILE="$(mktemp)"
          remove_empty_sections "${TMP_FILE}" | tee "${CHANGES_FILE}"

          cat > "./doc/content/whats-new/${TAG}.md" <<EOF
          ---
          date: ${DATE}
          title: "${TAG//v/}"
          featured: {}
          ---
          EOF
          cat "${CHANGES_FILE}" >> "./doc/content/whats-new/${TAG}.md"

          # Update header
          sed -i "0,/## \[Unreleased\]/s//## \[${TAG}\] - ${DATE}/" 'CHANGELOG.md'

          cat >>'CHANGELOG.md' <<EOF
          ## [Unreleased]

          ### Added

          ### Changed

          ### Deprecated

          ### Removed

          ### Fixed

          ### Security

          EOF
      - name: Update upgrading
        working-directory: "./lorawan-stack-docs"
        env:
          TAG: "${{ github.event.inputs.tag }}"
        run: |
          cp ../lorawan-stack-aws/UPGRADING.md .

          # Update header
          sed -i "0,/## Unreleased/s//## ${TAG}/" 'UPGRADING.md'

          cat >>'UPGRADING.md' <<EOF
          ## Unreleased

          EOF

          cat 'UPGRADING.md' > './doc/content/the-things-stack/host/aws/ecs/changelog/index.md'
      - name: Update doc version
        working-directory: "./lorawan-stack-docs"
        env:
          TAG: "${{ github.event.inputs.tag }}"
        run: |
          TAG="${TAG//v/}"  # Remove 'v' from tag
          sed -r "s/version = \"([0-9]+\.){2}[0-9]+\"/version = \"${TAG}\"/"
      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: "~1.21"
      - name: Download go dependencies
        working-directory: ./lorawan-stack/tools
        run: go mod download
      - name: Initialize mage binary cache
        id: mage-cache
        uses: actions/cache@v3
        with:
          path: ./lorawan-stack/tools/bin/mage
          key: ${{ runner.os }}-mage-${{ hashFiles('lorawan-stack/tools/**') }}
      - name: Make mage
        if: steps.mage-cache.outputs.cache-hit != 'true'
        working-directory: ./lorawan-stack
        run: make tools/bin/mage
      - name: Generate hugo data
        working-directory: "./lorawan-stack"
        run: tools/bin/mage ttiProto:hugoData
      - name: Sync hugo data
        working-directory: "./lorawan-stack-docs"
        run: |
          rsync --recursive --delete --remove-source-files '../lorawan-stack/api/ttn.lorawan.v3/' './doc/data/api/ttn.lorawan.v3/'
          rsync --recursive --delete --remove-source-files '../lorawan-stack/api/tti.lorawan.v3/' './doc/data/api/tti.lorawan.v3/'
      - name: Export CLI documentation
        working-directory: "./lorawan-stack"
        run: |
          go build -tags 'tti' './cmd/tti-lw-cli'

          HOME='$HOME' ./tti-lw-cli 'gen-md-doc' -o '../lorawan-stack-docs/doc/content/ttn-lw-cli'
          HOME='$HOME' ./tti-lw-cli 'gen-json-tree' -o '../lorawan-stack-docs/doc/data/commands'

          # Replace links to 'end-devices/templates' with 'templates' as they are not exported correctly.
          sed -i 's/end-devices_templates/templates/g' '../lorawan-stack-docs/doc/content/ttn-lw-cli/ttn-lw-cli_end-devices.md'
      - name: Upload artifacts to validate files
        uses: actions/upload-artifact@v3
        with:
          name: Changed files
          path: |
            lorawan-stack-docs/doc/content/the-things-stack/host/aws/ecs/changelog/index.md
            lorawan-stack-docs/doc/content/whats-new/${{ github.event.inputs.tag }}.md
